"""
Django settings for ams project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a_bcsxsuj0e_j1_7i!7e7e*y3_z=a)+a)&w9gd8p!ly8y@h$2o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'rest_framework_simplejwt',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'amshome',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
]
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'ams.urls'


REST_FRAMEWORK = {

  'DEFAULT_AUTHENTICATION_CLASSES': (
      'rest_framework_simplejwt.authentication.JWTAuthentication',
      'rest_framework.authentication.BasicAuthentication',

  )
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SIGNING_KEY = '''-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAyl4YZDtEqWr8wz2ss9/HFRVk+F4arVyeq4Hob4x7/3uO8SdW
TDpRzlNshnXmPsgRQ1x+VmFSZixHXXjsoKF1xKyZdH2b0IIHS7YshJzayle93KCq
GPcHi8hhJxTNBfGUwcVyTMd4lnVVab0v36FwjZz214vPXxJjd82duwTW0UF4PmvC
hPhrslSbEvOot3kLBJFe4Lu30qNFM1eiRYQ7/pAL77DvJJNxip94KE1sgNOSIpX2
K1aA2EfX2GmnxcnMrT06sZMldpQ8L89B3ekq/NiXtQoyDuJWUpW3lptTnn+y9SAf
vhsEQiziHFkMkVgywJTo8dn01HwYRcD6RrdcDQIDAQABAoIBAQCWlm6QJ4pwh6yP
nNVnBJ6gkcsRBvXTC5kHByRv3ZpoAwnbaepNzxgQ8QNRC2rKTRaLich5fvJSFaEF
bXaoEX4RXF7U0KOiBSBotqdqB07IQ4KFKwloimqTGgkxi8kFI0AO8V6cw9J4I9fr
V1zIjNm0h5knzGID3Ssne1pkULWKAFn/818s870fBYGRztfB+EwDXqiF9MftGo1N
ulBsnjBnr6FSqwJeoP76zH9vPOHFa21qw0ID4AHqDR7d/rKu4E7JJ9w6xlaPCIWK
cseN/kff9pN39v3Tdw4dNUkDNtsUgUppjBwFBjVdXaYjqhd2yxhUKakckONrlY0g
ITXx7uABAoGBAPfZ68i02k72cpog9aRmSVHLg/vv0jOQTeh1B74ArUetyo8iX3oo
9ue4uKE3KGV6DU6TVI1WlIAnrxV7EFCDtwFzn2gqLLdrtlf98PK7aK9HR8Z6hIm9
cKFj4s8y7Z/aBSwgox9TBGsX3Mkcm+OcKrzukXQUyW8Gs3z7Kfun1tVRAoGBANEF
WoVm3Q0ubkNXs41MvBSgTaj2zjstqLWPkuzMqHCW0YjiazcdsYxcl5Vz2gT/pmrA
DMPWmFBCUtVJtU5IsWDYPN7HDPlaU15iSWKdxJFjQ5zpKlScFdBf5hvUj6SW+bFF
loFWFEarOI/r1QnggLLM9rRTsHBSMB60gmKitxv9AoGBAKZ5LeCycMuGxvT1XGie
93JEIxNuQp61t06ChL+/DqRNe/dl3AFeUHDV5tUKCk0WjKeRV8JTPA1UGkpwTUX3
Ik2MTq6VXVGZvHEftN4kuKy6UOBkXG9z2ZndUHNhPrAWrVC1Xztj9FzGO1qtp5ta
wm4CQ5pXd/Dl7FrvDITmd+rxAoGAQhSONKR7eAJYy6N7WU2MHH09cBBuzJi3wIae
bYyaJ9YWck8alDcn/Xb8WTxiDbiA9Ti4EGXUi3McWt/NmO00XqiePdPyDxb2Sl2K
U8oK7efS5VV1k4AxCUp4Jg5CR0ePsvKMDWGYUWsqG530IQY/yccwq3vVyPzCx8JL
gkFs4EUCgYEAmoQDygglIRLgJiIyYbInIkZi8/5TKNiUs0xXrHC+nYeMughec5ab
bzmGvp29R0ZTyB0Mabff3eTRnjGLzECc+PkAE+NoV+NacHykqU0IB2l6f5MlJAKB
1Joq2BDczNTW2w6ss9EVo1qXwcOPEXN4MD4bFKcW7+noU2UP7d+3bDs=
-----END RSA PRIVATE KEY-----'''


VERIFYING_KEY = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyl4YZDtEqWr8wz2ss9/H
FRVk+F4arVyeq4Hob4x7/3uO8SdWTDpRzlNshnXmPsgRQ1x+VmFSZixHXXjsoKF1
xKyZdH2b0IIHS7YshJzayle93KCqGPcHi8hhJxTNBfGUwcVyTMd4lnVVab0v36Fw
jZz214vPXxJjd82duwTW0UF4PmvChPhrslSbEvOot3kLBJFe4Lu30qNFM1eiRYQ7
/pAL77DvJJNxip94KE1sgNOSIpX2K1aA2EfX2GmnxcnMrT06sZMldpQ8L89B3ekq
/NiXtQoyDuJWUpW3lptTnn+y9SAfvhsEQiziHFkMkVgywJTo8dn01HwYRcD6Rrdc
DQIDAQAB
-----END PUBLIC KEY-----'''


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "RS256",
    "SIGNING_KEY": SIGNING_KEY,
    "VERIFYING_KEY": VERIFYING_KEY,
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}






JWT_ALGORITHM = "RS256"
JWT_PRIVATE_KEY_PATH = SIGNING_KEY
JWT_PUBLIC_KEY_PATH = VERIFYING_KEY
JWT_ISSUER = "ams"
JWT_AUDIENCE = "login"
JWT_EXPIRATION_DELTA = timedelta(days=1)






AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

WSGI_APPLICATION = 'ams.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ams',
        'USER': 'root',
        'PASSWORD': 'cdac@123'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

ANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





#---------------------------Key--------------------------------#
FKEY = b'uNBeNeqFSnT9cINY6a9hww=='
# -------------------------------------------------------------#




